from __future__ import annotations

from typing import Any, Dict, List


def _rule(rule_id: str, name: str, expression: str, note: str) -> Dict[str, str]:
    return {"ruleId": rule_id, "name": name, "expression": expression, "note": note}


def _backtest(total: float, annualized: float, drawdown: float, volatility: float, sharpe: float, win_rate: float, turnover: float, benchmark: str, excess: float) -> Dict[str, Any]:
    return {
        "startDate": "2023-01-01",
        "endDate": "2026-03-31",
        "totalReturn": total,
        "annualizedReturn": annualized,
        "maxDrawdown": drawdown,
        "volatility": volatility,
        "sharpe": sharpe,
        "winRate": win_rate,
        "turnover": turnover,
        "benchmark": benchmark,
        "excessReturn": excess,
    }


def get_static_strategy_seed() -> List[Dict[str, Any]]:
    """Return AlphaTrace read-only strategy seed for Strategy Lab real mode."""
    updated_at = "2026-04-30T00:00:00+08:00"
    return [
        {
            "strategyId": "strategy_etf_rotation_csi300_growth",
            "strategyName": "沪深300与成长ETF轮动策略",
            "name": "沪深300与成长ETF轮动策略",
            "strategyType": "ETF_ROTATION",
            "style": "GROWTH_AGGRESSIVE",
            "styleLabel": "成长进攻",
            "status": "ACTIVE",
            "lifecycleStatus": "RUNNING",
            "description": "基于宽基动量、估值修复和流动性环境，在沪深300ETF与创业板ETF之间进行月度轮动。",
            "assetTypes": ["ETF", "INDEX"],
            "relatedAssetIds": ["asset_etf_510300", "asset_etf_159915", "asset_index_000300", "asset_index_399006"],
            "relatedEvidenceIds": ["ev_static_510300_snapshot_001", "ev_static_csi300_macro_001", "ev_static_csi300_research_001"],
            "relatedDecisionIds": [],
            "relatedPortfolioIds": ["portfolio_etf_core_001"],
            "frequency": "monthly",
            "horizon": "medium_term",
            "riskLevel": "medium_high",
            "ownerAgentId": "strategy_agent_etf_rotation",
            "rules": [
                _rule("rule_momentum_rank", "动量排序", "rank_3m_return(ETF universe) desc", "优先选择近三个月相对强势的宽基或成长ETF。"),
                _rule("rule_liquidity", "流动性过滤", "liquidity_score >= 80", "剔除成交活跃度不足的ETF。"),
            ],
            "signals": ["3M momentum", "liquidity score", "index breadth"],
            "riskControls": ["单一ETF权重不超过60%", "最大回撤超过8%触发降仓观察"],
            "backtestSummary": _backtest(38.4, 11.8, -13.2, 18.6, 0.92, 58.0, 145.0, "沪深300指数", 7.6),
            "applicableScenarios": ["成长风格占优", "市场流动性改善", "宽基轮动明确"],
            "invalidationConditions": ["创业板波动快速放大", "宽基指数跌破长期趋势"],
            "majorRisks": ["风格切换过快", "行业集中度上升"],
            "triggerConditions": ["动量排名变化", "成交额低于阈值", "指数风险事件"],
            "rebalanceFrequency": "monthly",
            "riskConstraints": ["单资产权重上限60%", "组合年化波动目标20%以内"],
            "observationIndicators": ["ETF折溢价", "指数成交额", "北向资金趋势"],
            "createdAt": "2026-01-15T00:00:00+08:00",
            "updatedAt": updated_at,
            "tags": ["ETF轮动", "成长", "宽基", "中期配置"],
            "metadata": {"staticSeed": True},
        },
        {
            "strategyId": "strategy_fund_selection_balanced",
            "strategyName": "平衡型基金筛选策略",
            "name": "平衡型基金筛选策略",
            "strategyType": "FUND_SELECTION",
            "style": "LOW_VOL_STEADY",
            "styleLabel": "低波稳健",
            "status": "ACTIVE",
            "lifecycleStatus": "VERIFIED",
            "description": "结合基金经理稳定性、回撤控制、持仓分散度和基金季报质量，筛选中等风险平衡型基金。",
            "assetTypes": ["FUND"],
            "relatedAssetIds": ["asset_fund_000001", "asset_fund_110022"],
            "relatedEvidenceIds": ["ev_static_fund_000001_quarterly_001", "ev_static_fund_000001_news_001"],
            "relatedDecisionIds": [],
            "relatedPortfolioIds": ["portfolio_multi_asset_001"],
            "frequency": "quarterly",
            "horizon": "long_term",
            "riskLevel": "medium",
            "ownerAgentId": "fund_selection_agent",
            "rules": [
                _rule("rule_drawdown", "回撤过滤", "max_drawdown_1y <= peer_p75", "剔除同类中回撤过大的基金。"),
                _rule("rule_style_drift", "风格漂移", "style_drift_score <= 0.35", "控制基金实际持仓与目标风格偏离。"),
            ],
            "signals": ["manager tenure", "drawdown control", "style exposure"],
            "riskControls": ["同一基金公司权重不超过40%", "单基金权重不超过25%"],
            "backtestSummary": _backtest(24.6, 7.9, -8.8, 10.4, 0.88, 61.0, 32.0, "偏股混合基金指数", 3.2),
            "applicableScenarios": ["稳健配置", "权益中枢震荡", "基金经理风格稳定"],
            "invalidationConditions": ["基金经理变更", "季报暴露显著漂移"],
            "majorRisks": ["季报滞后", "隐含行业集中"],
            "triggerConditions": ["季度报告更新", "净值回撤超过阈值"],
            "rebalanceFrequency": "quarterly",
            "riskConstraints": ["单基金权重上限25%", "基金公司集中度上限40%"],
            "observationIndicators": ["基金净值回撤", "重仓股变化", "同类排名"],
            "createdAt": "2026-01-18T00:00:00+08:00",
            "updatedAt": updated_at,
            "tags": ["基金筛选", "低波", "季报", "稳健"],
            "metadata": {"staticSeed": True},
        },
        {
            "strategyId": "strategy_future_timing_if",
            "strategyName": "沪深300股指期货择时策略",
            "name": "沪深300股指期货择时策略",
            "strategyType": "FUTURES_TIMING",
            "style": "TREND_TIMING",
            "styleLabel": "趋势择时",
            "status": "ACTIVE",
            "lifecycleStatus": "RUNNING",
            "description": "结合股指期货基差、持仓量、指数趋势和宏观事件，判断IF主力合约配置时点。",
            "assetTypes": ["FUTURE", "INDEX"],
            "relatedAssetIds": ["asset_future_if_main", "asset_index_000300"],
            "relatedEvidenceIds": ["ev_static_if_future_snapshot_001", "ev_static_csi300_macro_001"],
            "relatedDecisionIds": [],
            "relatedPortfolioIds": ["portfolio_multi_asset_001"],
            "frequency": "weekly",
            "horizon": "short_term",
            "riskLevel": "high",
            "ownerAgentId": "futures_timing_agent",
            "rules": [
                _rule("rule_basis", "基差信号", "basis_zscore > -1.5", "极端贴水修复时观察配置窗口。"),
                _rule("rule_oi", "持仓确认", "open_interest_trend >= 0", "持仓量改善时提高信号可信度。"),
            ],
            "signals": ["basis", "open interest", "index trend", "macro event"],
            "riskControls": ["保证金风险预警", "基差快速扩张时降权"],
            "backtestSummary": _backtest(29.8, 9.4, -16.5, 22.4, 0.64, 53.0, 210.0, "沪深300指数", 4.1),
            "applicableScenarios": ["趋势明确", "基差修复", "市场风险偏好回升"],
            "invalidationConditions": ["基差继续恶化", "指数跌破关键支撑"],
            "majorRisks": ["杠杆波动", "流动性跳变", "政策事件"],
            "triggerConditions": ["基差分位变化", "持仓量异常", "宏观事件"],
            "rebalanceFrequency": "weekly",
            "riskConstraints": ["期货名义敞口上限20%", "单周亏损超过3%触发复核"],
            "observationIndicators": ["IF基差", "主力合约成交量", "沪深300波动率"],
            "createdAt": "2026-02-01T00:00:00+08:00",
            "updatedAt": updated_at,
            "tags": ["期货择时", "股指期货", "基差", "趋势"],
            "metadata": {"staticSeed": True},
        },
        {
            "strategyId": "strategy_multi_asset_core",
            "strategyName": "多资产核心配置策略",
            "name": "多资产核心配置策略",
            "strategyType": "MULTI_ASSET_ALLOCATION",
            "style": "MACRO_ALLOCATION",
            "styleLabel": "宏观配置",
            "status": "ACTIVE",
            "lifecycleStatus": "VERIFIED",
            "description": "在ETF、基金、股指期货和黄金期货之间，根据宏观周期和风险预算进行核心配置。",
            "assetTypes": ["ETF", "FUND", "FUTURE", "INDEX"],
            "relatedAssetIds": ["asset_etf_510300", "asset_fund_000001", "asset_future_au_main", "asset_index_000300"],
            "relatedEvidenceIds": ["ev_static_macro_policy_001", "ev_static_510300_snapshot_001", "ev_static_fund_000001_quarterly_001"],
            "relatedDecisionIds": [],
            "relatedPortfolioIds": ["portfolio_multi_asset_001"],
            "frequency": "monthly",
            "horizon": "medium_term",
            "riskLevel": "medium",
            "ownerAgentId": "allocation_agent",
            "rules": [
                _rule("rule_risk_budget", "风险预算", "risk_contribution <= target + tolerance", "控制权益、商品和现金的风险贡献。"),
                _rule("rule_macro_regime", "宏观状态", "macro_regime in [recovery, neutral]", "宏观环境改善时提高权益权重。"),
            ],
            "signals": ["macro regime", "volatility", "gold trend", "equity breadth"],
            "riskControls": ["权益风险贡献上限55%", "商品敞口上限20%"],
            "backtestSummary": _backtest(31.2, 9.7, -10.4, 12.6, 0.96, 60.0, 62.0, "60/40组合", 5.9),
            "applicableScenarios": ["中期资产配置", "宏观周期切换", "风险预算管理"],
            "invalidationConditions": ["资产相关性快速上升", "政策冲击导致风险预算失效"],
            "majorRisks": ["跨资产相关性上升", "黄金与权益同步回撤"],
            "triggerConditions": ["宏观状态更新", "组合波动超阈值"],
            "rebalanceFrequency": "monthly",
            "riskConstraints": ["组合波动率目标15%以内", "单资产类别风险贡献上限55%"],
            "observationIndicators": ["权益风险溢价", "黄金趋势", "债券收益率"],
            "createdAt": "2026-02-10T00:00:00+08:00",
            "updatedAt": updated_at,
            "tags": ["多资产配置", "宏观", "风险预算"],
            "metadata": {"staticSeed": True},
        },
        {
            "strategyId": "strategy_dividend_defensive",
            "strategyName": "红利防御规则策略",
            "name": "红利防御规则策略",
            "strategyType": "RULE_BASED",
            "style": "DIVIDEND_DEFENSIVE",
            "styleLabel": "红利防御",
            "status": "ACTIVE",
            "lifecycleStatus": "VERIFIED",
            "description": "在权益波动上升时提高红利和低波资产权重，作为组合防御模块。",
            "assetTypes": ["ETF", "INDEX"],
            "relatedAssetIds": ["asset_etf_510300", "asset_index_000300"],
            "relatedEvidenceIds": ["ev_static_510300_fee_001", "ev_static_macro_policy_001"],
            "relatedDecisionIds": [],
            "relatedPortfolioIds": ["portfolio_etf_core_001", "portfolio_multi_asset_001"],
            "frequency": "monthly",
            "horizon": "medium_term",
            "riskLevel": "low_medium",
            "ownerAgentId": "risk_allocation_agent",
            "rules": [
                _rule("rule_vol_guard", "波动防御", "market_volatility > threshold", "市场波动上行时提高防御权重。"),
                _rule("rule_dividend_quality", "红利质量", "dividend_quality_score >= 80", "优先高分红质量资产。"),
            ],
            "signals": ["market volatility", "dividend quality", "low volatility factor"],
            "riskControls": ["低流动性资产剔除", "行业集中度限制"],
            "backtestSummary": _backtest(21.5, 6.8, -7.6, 9.8, 0.82, 63.0, 48.0, "红利低波指数", 2.4),
            "applicableScenarios": ["震荡市", "波动率上升", "防御配置"],
            "invalidationConditions": ["成长风格显著占优", "红利拥挤度过高"],
            "majorRisks": ["收益弹性不足", "行业拥挤"],
            "triggerConditions": ["波动率升破阈值", "红利指数相对强度改善"],
            "rebalanceFrequency": "monthly",
            "riskConstraints": ["单行业暴露不超过30%", "低流动性资产剔除"],
            "observationIndicators": ["红利因子收益", "低波因子收益", "行业集中度"],
            "createdAt": "2026-02-15T00:00:00+08:00",
            "updatedAt": updated_at,
            "tags": ["红利防御", "规则策略", "低波"],
            "metadata": {"staticSeed": True},
        },
        {
            "strategyId": "strategy_growth_offensive",
            "strategyName": "成长进攻 Agent 生成策略",
            "name": "成长进攻 Agent 生成策略",
            "strategyType": "AGENT_GENERATED",
            "style": "GROWTH_AGGRESSIVE",
            "styleLabel": "成长进攻",
            "status": "ACTIVE",
            "lifecycleStatus": "RUNNING",
            "description": "由 Agent 研究链路生成的成长风格配置策略，结合证据质量、趋势和风险约束动态调整。",
            "assetTypes": ["ETF", "FUND"],
            "relatedAssetIds": ["asset_etf_159915", "asset_fund_110022"],
            "relatedEvidenceIds": ["ev_static_csi300_research_001", "ev_static_fund_000001_news_001"],
            "relatedDecisionIds": [],
            "relatedPortfolioIds": ["portfolio_etf_core_001"],
            "frequency": "monthly",
            "horizon": "medium_term",
            "riskLevel": "medium_high",
            "ownerAgentId": "agent_generated_strategy",
            "rules": [
                _rule("rule_evidence_score", "证据质量", "evidence_score >= 80", "只在证据质量较高时提高成长权重。"),
                _rule("rule_trend_confirm", "趋势确认", "trend_score >= 0.6", "要求趋势指标确认。"),
            ],
            "signals": ["evidence score", "trend score", "growth style momentum"],
            "riskControls": ["回撤预警", "风格暴露上限"],
            "backtestSummary": _backtest(42.1, 12.9, -18.0, 23.5, 0.74, 55.0, 118.0, "创业板指", 6.8),
            "applicableScenarios": ["风险偏好回升", "成长景气改善", "证据质量充足"],
            "invalidationConditions": ["证据评分下降", "成长风格拥挤"],
            "majorRisks": ["波动大", "估值压缩", "风格反转"],
            "triggerConditions": ["证据评分变化", "趋势评分变化"],
            "rebalanceFrequency": "monthly",
            "riskConstraints": ["成长资产权重上限50%", "回撤超过10%降仓复核"],
            "observationIndicators": ["成长指数强度", "研报分歧度", "成交额变化"],
            "createdAt": "2026-02-20T00:00:00+08:00",
            "updatedAt": updated_at,
            "tags": ["Agent生成策略", "成长", "证据链"],
            "metadata": {"staticSeed": True},
        },
        {
            "strategyId": "strategy_risk_parity",
            "strategyName": "风险平价多资产策略",
            "name": "风险平价多资产策略",
            "strategyType": "MULTI_ASSET_ALLOCATION",
            "style": "RISK_PARITY",
            "styleLabel": "风险平价",
            "status": "ACTIVE",
            "lifecycleStatus": "VERIFIED",
            "description": "以风险贡献均衡为核心，在权益、基金和商品期货之间动态配置。",
            "assetTypes": ["ETF", "FUND", "FUTURE"],
            "relatedAssetIds": ["asset_etf_510300", "asset_fund_000001", "asset_future_au_main"],
            "relatedEvidenceIds": ["ev_static_macro_policy_001", "ev_static_510300_snapshot_001"],
            "relatedDecisionIds": [],
            "relatedPortfolioIds": ["portfolio_multi_asset_001"],
            "frequency": "monthly",
            "horizon": "long_term",
            "riskLevel": "medium",
            "ownerAgentId": "risk_parity_agent",
            "rules": [
                _rule("rule_risk_equal", "风险贡献均衡", "abs(risk_contribution - target) <= tolerance", "根据资产波动和相关性调整权重。"),
                _rule("rule_corr_guard", "相关性保护", "average_correlation <= 0.65", "相关性升高时降低总风险预算。"),
            ],
            "signals": ["volatility", "correlation", "risk contribution"],
            "riskControls": ["风险贡献偏离预警", "相关性升高降风险"],
            "backtestSummary": _backtest(27.9, 8.7, -9.9, 11.2, 0.93, 62.0, 58.0, "风险平价基准", 4.5),
            "applicableScenarios": ["长期配置", "风险预算明确", "多资产低相关"],
            "invalidationConditions": ["相关性系统性升高", "波动率估计失真"],
            "majorRisks": ["相关性突变", "商品波动放大"],
            "triggerConditions": ["风险贡献偏离", "资产相关性升高"],
            "rebalanceFrequency": "monthly",
            "riskConstraints": ["单资产风险贡献上限35%", "组合波动率目标12%"],
            "observationIndicators": ["滚动波动率", "资产相关性", "风险贡献"],
            "createdAt": "2026-03-01T00:00:00+08:00",
            "updatedAt": updated_at,
            "tags": ["风险平价", "多资产", "风险预算"],
            "metadata": {"staticSeed": True},
        },
        {
            "strategyId": "strategy_mean_reversion_etf",
            "strategyName": "ETF均值回归策略",
            "name": "ETF均值回归策略",
            "strategyType": "ETF_ROTATION",
            "style": "MEAN_REVERSION",
            "styleLabel": "均值回归",
            "status": "PAUSED",
            "lifecycleStatus": "PAUSED",
            "description": "在宽基ETF偏离均衡区间后等待均值回归窗口，强调低换手和风险确认。",
            "assetTypes": ["ETF", "INDEX"],
            "relatedAssetIds": ["asset_etf_510300", "asset_index_000300"],
            "relatedEvidenceIds": ["ev_static_510300_snapshot_001", "ev_static_510300_fee_001"],
            "relatedDecisionIds": [],
            "relatedPortfolioIds": ["portfolio_etf_core_001"],
            "frequency": "weekly",
            "horizon": "short_term",
            "riskLevel": "medium",
            "ownerAgentId": "mean_reversion_agent",
            "rules": [
                _rule("rule_zscore", "偏离度", "price_zscore <= -1.2", "价格偏离均衡区间后观察反弹窗口。"),
                _rule("rule_confirm", "确认信号", "breadth_recovery == true", "等待市场广度确认，避免过早介入。"),
            ],
            "signals": ["zscore", "market breadth", "liquidity"],
            "riskControls": ["趋势破位停止介入", "成交量萎缩时降低权重"],
            "backtestSummary": _backtest(18.2, 5.9, -7.2, 10.8, 0.68, 57.0, 74.0, "沪深300ETF", 1.8),
            "applicableScenarios": ["震荡市", "宽基超跌修复", "流动性稳定"],
            "invalidationConditions": ["下跌趋势延续", "成交量继续萎缩"],
            "majorRisks": ["左侧介入过早", "趋势性下跌"],
            "triggerConditions": ["价格偏离度扩大", "市场广度恢复"],
            "rebalanceFrequency": "weekly",
            "riskConstraints": ["单次试仓不超过20%", "连续失败后暂停"],
            "observationIndicators": ["价格zscore", "市场广度", "ETF成交额"],
            "createdAt": "2026-03-12T00:00:00+08:00",
            "updatedAt": updated_at,
            "tags": ["ETF", "均值回归", "低换手"],
            "metadata": {"staticSeed": True},
        },
    ]
