from __future__ import annotations

from typing import Any, Dict, List


def _holding(
    asset_id: str,
    symbol: str,
    name: str,
    asset_type: str,
    weight: float,
    target_weight: float,
    quantity: float,
    market_value: float,
    cost_basis: float,
    latest_price: float,
    pnl_pct: float,
    action: str,
) -> Dict[str, Any]:
    avg_cost = cost_basis / quantity if quantity else 0
    unrealized = market_value * pnl_pct / 100
    return {
        "assetId": asset_id,
        "symbol": symbol,
        "assetName": name,
        "assetType": asset_type,
        "weight": weight,
        "targetWeight": target_weight,
        "quantity": quantity,
        "marketValue": market_value,
        "costBasis": cost_basis,
        "avgCost": avg_cost,
        "latestPrice": latest_price,
        "unrealizedPnl": unrealized,
        "unrealizedPnlPct": pnl_pct,
        "returnContribution": weight * pnl_pct,
        "riskContribution": weight * (1.3 if asset_type == "FUTURE" else 1.0) * 100,
        "actionSuggestion": action,
    }


def _recommendation(
    rec_id: str,
    action: str,
    asset_id: str,
    from_weight: float,
    to_weight: float,
    reason: str,
    expected: str,
    risk: str,
    evidence_ids: List[str],
    status: str,
    priority: str = "MEDIUM",
) -> Dict[str, Any]:
    return {
        "recommendationId": rec_id,
        "action": action,
        "assetId": asset_id,
        "fromWeight": from_weight,
        "toWeight": to_weight,
        "reason": reason,
        "priority": priority,
        "expectedImpact": expected,
        "riskImpact": risk,
        "relatedEvidenceIds": evidence_ids,
        "evidenceIds": evidence_ids,
        "relatedDecisionIds": [],
        "status": status,
    }


def get_static_portfolio_seed() -> List[Dict[str, Any]]:
    updated_at = "2026-04-30T00:00:00+08:00"
    return [
        {
            "portfolioId": "portfolio_etf_core_001",
            "name": "ETF 核心配置组合",
            "objective": "以宽基 ETF 为核心，兼顾成长弹性与防御风险预算。",
            "riskLevel": "MEDIUM",
            "status": "ACTIVE",
            "description": "面向中期资产配置的 ETF 核心组合，连接资产研究、策略轮动和调仓建议。",
            "baseCurrency": "CNY",
            "totalValue": 12_800_000,
            "cashWeight": 0.08,
            "updatedAt": updated_at,
            "relatedAssetIds": ["asset_etf_510300", "asset_etf_159915", "asset_index_000300"],
            "relatedStrategyIds": ["strategy_etf_rotation_csi300_growth", "strategy_mean_reversion_etf", "strategy_dividend_defensive"],
            "relatedDecisionIds": [],
            "holdings": [
                _holding("asset_etf_510300", "510300.SH", "沪深300ETF", "ETF", 0.44, 0.46, 2_400_000, 9_456_000, 9_144_000, 3.94, 3.41, "INCREASE"),
                _holding("asset_etf_159915", "159915.SZ", "创业板ETF", "ETF", 0.28, 0.24, 1_900_000, 4_180_000, 4_030_000, 2.20, 3.72, "DECREASE"),
                _holding("asset_index_000300", "000300.SH", "沪深300指数", "INDEX", 0.20, 0.22, 0, 2_560_000, 2_480_000, 0, 3.23, "HOLD"),
            ],
            "exposures": [
                {"dimension": "asset_class", "name": "ETF", "value": 72},
                {"dimension": "asset_class", "name": "Index", "value": 20},
                {"dimension": "cash", "name": "Cash", "value": 8},
                {"dimension": "style", "name": "Growth", "value": 31},
                {"dimension": "style", "name": "Broad Market", "value": 52},
            ],
            "riskMetrics": {
                "volatility": 12.2,
                "maxDrawdown": 9.8,
                "sharpe": 1.02,
                "sortino": 1.42,
                "beta": 0.91,
                "var95": 2.2,
                "concentration": 44.0,
                "liquidityScore": 86.0,
                "correlationRisk": 48.0,
                "riskScore": 42.0,
            },
            "rebalanceRecommendations": [
                _recommendation(
                    "rec_etf_core_001",
                    "INCREASE",
                    "asset_etf_510300",
                    0.44,
                    0.46,
                    "沪深300ETF流动性和证据质量较高，可温和提高核心仓位。",
                    "提升宽基 Beta 暴露并增强组合稳定性。",
                    "小幅增加权益集中度，需要持续监控回撤。",
                    ["ev_static_510300_snapshot_001", "ev_static_csi300_macro_001"],
                    "IN_REVIEW",
                ),
                _recommendation(
                    "rec_etf_core_002",
                    "DECREASE",
                    "asset_etf_159915",
                    0.28,
                    0.24,
                    "成长风格波动较高，建议释放部分风险预算。",
                    "降低组合短期波动。",
                    "若成长风格继续走强，可能损失部分上行弹性。",
                    ["ev_static_csi300_research_001"],
                    "PENDING",
                ),
            ],
            "tags": ["ETF", "核心配置", "中期", "风险预算"],
            "metadata": {"staticSeed": True},
        },
        {
            "portfolioId": "portfolio_multi_asset_001",
            "name": "多资产配置组合",
            "objective": "在 ETF、基金、期货和指数之间管理多来源收益和风险贡献。",
            "riskLevel": "HIGH",
            "status": "REBALANCING",
            "description": "用于验证宏观配置、风险平价和期货择时策略的多资产组合。",
            "baseCurrency": "CNY",
            "totalValue": 18_600_000,
            "cashWeight": 0.06,
            "updatedAt": updated_at,
            "relatedAssetIds": ["asset_etf_510300", "asset_fund_000001", "asset_future_if_main", "asset_future_au_main", "asset_index_000300"],
            "relatedStrategyIds": ["strategy_multi_asset_core", "strategy_risk_parity", "strategy_future_timing_if", "strategy_fund_selection_balanced"],
            "relatedDecisionIds": [],
            "holdings": [
                _holding("asset_etf_510300", "510300.SH", "沪深300ETF", "ETF", 0.30, 0.32, 1_600_000, 6_304_000, 6_048_000, 3.94, 4.23, "INCREASE"),
                _holding("asset_fund_000001", "000001.OF", "平衡型基金样例", "FUND", 0.20, 0.18, 900_000, 1_962_000, 1_863_000, 2.18, 5.31, "DECREASE"),
                _holding("asset_future_if_main", "IF_MAIN.CFFEX", "沪深300股指期货", "FUTURE", 0.18, 0.16, 35, 2_842_000, 2_730_000, 4062, 4.10, "DECREASE"),
                _holding("asset_future_au_main", "AU_MAIN.SHFE", "黄金期货", "FUTURE", 0.16, 0.18, 22, 2_976_000, 2_860_000, 676, 4.06, "INCREASE"),
                _holding("asset_index_000300", "000300.SH", "沪深300指数", "INDEX", 0.10, 0.10, 0, 1_860_000, 1_820_000, 0, 2.20, "HOLD"),
            ],
            "exposures": [
                {"dimension": "asset_class", "name": "ETF", "value": 30},
                {"dimension": "asset_class", "name": "Fund", "value": 20},
                {"dimension": "asset_class", "name": "Futures", "value": 34},
                {"dimension": "asset_class", "name": "Index", "value": 10},
                {"dimension": "cash", "name": "Cash", "value": 6},
            ],
            "riskMetrics": {
                "volatility": 15.1,
                "maxDrawdown": 13.4,
                "sharpe": 0.91,
                "sortino": 1.25,
                "beta": 0.78,
                "var95": 3.1,
                "concentration": 30.0,
                "liquidityScore": 78.0,
                "correlationRisk": 54.0,
                "riskScore": 58.0,
            },
            "rebalanceRecommendations": [
                _recommendation(
                    "rec_multi_001",
                    "INCREASE",
                    "asset_future_au_main",
                    0.16,
                    0.18,
                    "黄金期货在宏观不确定性上升时提供组合对冲价值。",
                    "增强防御和分散收益来源。",
                    "商品波动可能提高保证金和情景风险。",
                    ["ev_static_macro_policy_001"],
                    "APPROVED",
                    "HIGH",
                ),
                _recommendation(
                    "rec_multi_002",
                    "DECREASE",
                    "asset_future_if_main",
                    0.18,
                    0.16,
                    "股指期货方向性 Beta 较高，当前组合回撤预算偏紧。",
                    "降低组合短期回撤尾部风险。",
                    "如果权益市场快速修复，可能降低反弹参与度。",
                    ["ev_static_if_future_snapshot_001", "ev_static_csi300_macro_001"],
                    "IN_REVIEW",
                ),
            ],
            "tags": ["多资产", "宏观配置", "风险平价", "期货"],
            "metadata": {"staticSeed": True},
        },
        {
            "portfolioId": "portfolio_defensive_income_001",
            "name": "稳健防御组合",
            "objective": "以低波、红利和风险平价思想构建稳健防御型组合。",
            "riskLevel": "LOW",
            "status": "WATCH",
            "description": "用于低波稳健、红利防御和组合风险预算观察的防御配置组合。",
            "baseCurrency": "CNY",
            "totalValue": 9_200_000,
            "cashWeight": 0.12,
            "updatedAt": updated_at,
            "relatedAssetIds": ["asset_etf_510300", "asset_fund_000001", "asset_fund_110022", "asset_future_au_main"],
            "relatedStrategyIds": ["strategy_dividend_defensive", "strategy_risk_parity", "strategy_fund_selection_balanced"],
            "relatedDecisionIds": [],
            "holdings": [
                _holding("asset_etf_510300", "510300.SH", "沪深300ETF", "ETF", 0.26, 0.26, 1_000_000, 3_940_000, 3_810_000, 3.94, 3.41, "HOLD"),
                _holding("asset_fund_000001", "000001.OF", "平衡型基金样例", "FUND", 0.24, 0.26, 720_000, 1_569_600, 1_490_400, 2.18, 5.31, "INCREASE"),
                _holding("asset_fund_110022", "110022.OF", "指数增强基金样例", "FUND", 0.22, 0.20, 650_000, 1_430_000, 1_398_000, 2.20, 2.29, "DECREASE"),
                _holding("asset_future_au_main", "AU_MAIN.SHFE", "黄金期货", "FUTURE", 0.16, 0.16, 12, 1_624_000, 1_558_000, 676, 4.24, "HOLD"),
            ],
            "exposures": [
                {"dimension": "asset_class", "name": "ETF", "value": 26},
                {"dimension": "asset_class", "name": "Fund", "value": 46},
                {"dimension": "asset_class", "name": "Futures", "value": 16},
                {"dimension": "cash", "name": "Cash", "value": 12},
                {"dimension": "style", "name": "Low Volatility", "value": 42},
            ],
            "riskMetrics": {
                "volatility": 8.9,
                "maxDrawdown": 6.8,
                "sharpe": 1.12,
                "sortino": 1.58,
                "beta": 0.54,
                "var95": 1.6,
                "concentration": 26.0,
                "liquidityScore": 74.0,
                "correlationRisk": 38.0,
                "riskScore": 32.0,
            },
            "rebalanceRecommendations": [
                _recommendation(
                    "rec_defensive_001",
                    "INCREASE",
                    "asset_fund_000001",
                    0.24,
                    0.26,
                    "平衡型基金回撤控制和季报质量较好，可作为防御底仓。",
                    "增强组合稳健性。",
                    "可能降低组合上行弹性。",
                    ["ev_static_fund_000001_quarterly_001"],
                    "PENDING",
                )
            ],
            "tags": ["稳健", "红利防御", "低波", "风险平价"],
            "metadata": {"staticSeed": True},
        },
    ]
