from __future__ import annotations

from typing import Any, Dict, List


STATIC_ASSET_SEED: List[Dict[str, Any]] = [
    {
        "assetId": "asset_etf_510300",
        "id": "asset_etf_510300",
        "symbol": "510300.SH",
        "name": "沪深300ETF",
        "assetType": "ETF",
        "market": "A股",
        "currency": "CNY",
        "tags": ["宽基", "红利", "低波", "core", "large_cap"],
        "description": "跟踪沪深300指数的大盘宽基 ETF，用于中国 A 股核心权益配置。",
        "updatedAt": "2026-04-28T16:00:00+08:00",
        "riskLevel": "medium",
        "liquidityLevel": "high",
        "relatedEvidenceIds": ["ev_static_510300_fee_001", "ev_static_510300_snapshot_001"],
        "aliases": ["510300.SH"],
        "metrics": {"liquidityScore": 93, "trackingError": 0.9, "expenseRatio": 0.5},
        "profile": {
            "trackingIndex": "CSI 300",
            "fundCompany": "Huatai-PineBridge",
            "aum": 341_000_000_000,
            "expenseRatio": 0.5,
            "trackingError": 0.9,
            "liquidityScore": 93,
            "premiumDiscount": 0.06,
            "holdings": [
                {"symbol": "600519.SH", "name": "Kweichow Moutai", "weight": 6.5, "sector": "Consumer"},
                {"symbol": "300750.SZ", "name": "CATL", "weight": 4.1, "sector": "Industrials"},
                {"symbol": "601318.SH", "name": "Ping An", "weight": 3.0, "sector": "Financials"},
            ],
            "exposures": [
                {"dimension": "sector", "name": "Financials", "value": 23.4},
                {"dimension": "sector", "name": "Industrials", "value": 16.1},
                {"dimension": "style", "name": "Large Cap", "value": 88.0},
            ],
        },
    },
    {
        "assetId": "asset_etf_159915",
        "id": "asset_etf_159915",
        "symbol": "159915.SZ",
        "name": "创业板ETF",
        "assetType": "ETF",
        "market": "A股",
        "currency": "CNY",
        "tags": ["成长", "宽基", "行业", "growth"],
        "description": "跟踪创业板指的成长风格 ETF，适合作为高弹性权益配置观察资产。",
        "updatedAt": "2026-04-28T16:00:00+08:00",
        "riskLevel": "high",
        "liquidityLevel": "high",
        "relatedEvidenceIds": [],
        "aliases": ["159915.SZ"],
        "metrics": {"liquidityScore": 90, "trackingError": 1.2, "expenseRatio": 0.5},
        "profile": {
            "trackingIndex": "ChiNext Index",
            "fundCompany": "E Fund",
            "aum": 96_000_000_000,
            "expenseRatio": 0.5,
            "trackingError": 1.2,
            "liquidityScore": 90,
            "premiumDiscount": -0.03,
            "holdings": [
                {"symbol": "300750.SZ", "name": "CATL", "weight": 17.8, "sector": "Industrials"},
                {"symbol": "300760.SZ", "name": "Mindray", "weight": 5.5, "sector": "Healthcare"},
                {"symbol": "300274.SZ", "name": "Sungrow", "weight": 4.6, "sector": "Industrials"},
            ],
            "exposures": [
                {"dimension": "sector", "name": "Industrials", "value": 34.0},
                {"dimension": "sector", "name": "Healthcare", "value": 18.5},
                {"dimension": "style", "name": "Growth", "value": 82.0},
            ],
        },
    },
    {
        "assetId": "asset_fund_000001",
        "id": "asset_fund_000001",
        "symbol": "000001.OF",
        "name": "平衡型基金样例",
        "assetType": "FUND",
        "market": "债券",
        "currency": "CNY",
        "tags": ["债券", "低波", "红利", "balanced"],
        "description": "偏稳健的平衡混合基金样例，关注红利资产和回撤控制。",
        "updatedAt": "2026-04-28T16:00:00+08:00",
        "riskLevel": "medium",
        "liquidityLevel": "medium",
        "relatedEvidenceIds": ["ev_static_fund_000001_quarterly_001"],
        "aliases": ["000001.OF"],
        "metrics": {"nav": 2.184, "drawdown": 11.6},
        "profile": {
            "fundManager": "Li Wen",
            "fundCompany": "China Universal",
            "fundType": "Balanced Hybrid",
            "nav": 2.184,
            "aum": 13_200_000_000,
            "expenseRatio": 1.2,
            "holdings": [
                {"symbol": "601988.SH", "name": "Bank of China", "weight": 5.1, "sector": "Financials"},
                {"symbol": "600900.SH", "name": "Yangtze Power", "weight": 4.7, "sector": "Utilities"},
                {"symbol": "CGB10Y", "name": "China Govt Bond 10Y", "weight": 18.4, "sector": "Fixed Income"},
            ],
            "styleExposure": [
                {"dimension": "style", "name": "Value", "value": 52.0},
                {"dimension": "style", "name": "Quality", "value": 28.0},
                {"dimension": "asset_class", "name": "Equity", "value": 65.0},
            ],
            "drawdown": 11.6,
        },
    },
    {
        "assetId": "asset_fund_110022",
        "id": "asset_fund_110022",
        "symbol": "110022.OF",
        "name": "指数增强基金样例",
        "assetType": "FUND",
        "market": "A股",
        "currency": "CNY",
        "tags": ["宽基", "成长", "增强", "quant"],
        "description": "以沪深300为基准的指数增强基金样例，关注超额收益和跟踪风险。",
        "updatedAt": "2026-04-28T16:00:00+08:00",
        "riskLevel": "medium",
        "liquidityLevel": "medium",
        "relatedEvidenceIds": [],
        "aliases": ["110022.OF"],
        "metrics": {"nav": 1.568, "drawdown": 14.2},
        "profile": {
            "fundManager": "Chen Yu",
            "fundCompany": "E Fund",
            "fundType": "Index Enhanced",
            "nav": 1.568,
            "aum": 8_800_000_000,
            "expenseRatio": 1.0,
            "holdings": [
                {"symbol": "600519.SH", "name": "Kweichow Moutai", "weight": 5.8, "sector": "Consumer"},
                {"symbol": "300750.SZ", "name": "CATL", "weight": 4.5, "sector": "Industrials"},
                {"symbol": "600036.SH", "name": "CMB", "weight": 3.4, "sector": "Financials"},
            ],
            "styleExposure": [
                {"dimension": "style", "name": "Quality", "value": 46.0},
                {"dimension": "style", "name": "Growth", "value": 31.0},
                {"dimension": "benchmark", "name": "CSI 300", "value": 92.0},
            ],
            "drawdown": 14.2,
        },
    },
    {
        "assetId": "asset_future_if_main",
        "id": "asset_future_if_main",
        "symbol": "IF_MAIN.CFFEX",
        "name": "沪深300股指期货",
        "assetType": "FUTURE",
        "market": "股指期货",
        "currency": "CNY",
        "tags": ["宏观", "股指期货", "对冲", "tactical"],
        "description": "沪深300股指期货主力连续合约，用于权益 beta 对冲和战术配置观察。",
        "updatedAt": "2026-04-28T15:15:00+08:00",
        "riskLevel": "high",
        "liquidityLevel": "high",
        "relatedEvidenceIds": ["ev_static_if_future_snapshot_001"],
        "aliases": ["IF_MAIN"],
        "metrics": {"openInterest": 138_420, "volume": 102_590, "basis": -12.4},
        "profile": {
            "exchange": "CFFEX",
            "contractCode": "IF",
            "underlying": "CSI 300",
            "mainContract": "IF2606",
            "openInterest": 138_420,
            "volume": 102_590,
            "basis": -12.4,
            "termStructure": [
                {"contract": "IF2605", "maturityDate": "2026-05-15", "annualizedBasis": -1.1},
                {"contract": "IF2606", "maturityDate": "2026-06-19", "annualizedBasis": -1.6},
                {"contract": "IF2609", "maturityDate": "2026-09-18", "annualizedBasis": -1.8},
            ],
            "inventoryNote": "Index futures; inventory not applicable.",
        },
    },
    {
        "assetId": "asset_future_au_main",
        "id": "asset_future_au_main",
        "symbol": "AU_MAIN.SHFE",
        "name": "黄金期货",
        "assetType": "FUTURE",
        "market": "商品期货",
        "currency": "CNY",
        "tags": ["商品", "宏观", "避险", "gold"],
        "description": "上海期货交易所黄金期货主力连续合约，关注实际利率、美元和避险需求。",
        "updatedAt": "2026-04-28T15:00:00+08:00",
        "riskLevel": "high",
        "liquidityLevel": "high",
        "relatedEvidenceIds": [],
        "aliases": ["AU_MAIN"],
        "metrics": {"openInterest": 92_400, "volume": 156_800, "basis": 1.6},
        "profile": {
            "exchange": "SHFE",
            "contractCode": "AU",
            "underlying": "Gold",
            "mainContract": "AU2606",
            "openInterest": 92_400,
            "volume": 156_800,
            "basis": 1.6,
            "termStructure": [
                {"contract": "AU2606", "maturityDate": "2026-06-15", "annualizedBasis": 0.8},
                {"contract": "AU2608", "maturityDate": "2026-08-15", "annualizedBasis": 1.0},
                {"contract": "AU2612", "maturityDate": "2026-12-15", "annualizedBasis": 1.3},
            ],
            "inventoryNote": "Exchange inventory stable; macro real-rate sensitivity remains high.",
        },
    },
    {
        "assetId": "asset_index_000300",
        "id": "asset_index_000300",
        "symbol": "000300.SH",
        "name": "沪深300指数",
        "assetType": "INDEX",
        "market": "A股",
        "currency": "CNY",
        "tags": ["宽基", "红利", "低波", "benchmark"],
        "description": "代表 A 股大盘蓝筹公司的核心宽基指数。",
        "updatedAt": "2026-04-28T15:00:00+08:00",
        "riskLevel": "medium",
        "liquidityLevel": "high",
        "relatedEvidenceIds": ["ev_static_csi300_macro_001", "ev_static_csi300_research_001"],
        "aliases": ["asset_index_csi300", "000300.SH"],
        "metrics": {"constituentCount": 300, "largeCapExposure": 88.0},
        "profile": {
            "provider": "China Securities Index",
            "constituents": [
                {"symbol": "600519.SH", "name": "Kweichow Moutai", "weight": 6.5},
                {"symbol": "300750.SZ", "name": "CATL", "weight": 4.1},
                {"symbol": "601318.SH", "name": "Ping An", "weight": 3.0},
            ],
            "sectorExposure": [
                {"dimension": "sector", "name": "Financials", "value": 23.4},
                {"dimension": "sector", "name": "Industrials", "value": 16.1},
                {"dimension": "sector", "name": "Consumer", "value": 14.2},
            ],
            "styleExposure": [
                {"dimension": "style", "name": "Large Cap", "value": 88.0},
                {"dimension": "style", "name": "Value", "value": 42.0},
                {"dimension": "style", "name": "Quality", "value": 26.0},
            ],
        },
    },
    {
        "assetId": "asset_index_399006",
        "id": "asset_index_399006",
        "symbol": "399006.SZ",
        "name": "创业板指",
        "assetType": "INDEX",
        "market": "A股",
        "currency": "CNY",
        "tags": ["成长", "宽基", "行业", "innovation"],
        "description": "创业板市场核心指数，集中反映成长与创新资产表现。",
        "updatedAt": "2026-04-28T15:00:00+08:00",
        "riskLevel": "high",
        "liquidityLevel": "high",
        "relatedEvidenceIds": [],
        "aliases": ["399006.SZ"],
        "metrics": {"constituentCount": 100, "growthExposure": 82.0},
        "profile": {
            "provider": "Shenzhen Securities Information",
            "constituents": [
                {"symbol": "300750.SZ", "name": "CATL", "weight": 17.8},
                {"symbol": "300760.SZ", "name": "Mindray", "weight": 5.5},
                {"symbol": "300274.SZ", "name": "Sungrow", "weight": 4.6},
            ],
            "sectorExposure": [
                {"dimension": "sector", "name": "Industrials", "value": 34.0},
                {"dimension": "sector", "name": "Healthcare", "value": 18.5},
                {"dimension": "sector", "name": "Technology", "value": 17.2},
            ],
            "styleExposure": [
                {"dimension": "style", "name": "Growth", "value": 82.0},
                {"dimension": "style", "name": "Momentum", "value": 35.0},
                {"dimension": "market_cap", "name": "Mid-Large", "value": 62.0},
            ],
        },
    },
]


def get_static_asset_seed() -> List[Dict[str, Any]]:
    return [dict(item) for item in STATIC_ASSET_SEED]

